// <auto-generated />
namespace HHCoApps.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RenameProductCategorytoCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameProductCategorytoCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201801130902585_Rename ProductCategory to Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
