//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHCoApps.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportLog
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime Created { get; set; }
        public int Quantity { get; set; }
        public decimal TotalCost { get; set; }
        public decimal TotalBaseCost { get; set; }
        public string ForeignCurrency { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
